name: Build and Deploy with HonKit
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install HonKit
      run: npm install -g honkit
        
    - name: Build with HonKit
      run: honkit build --reload . _book
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book
        force_orphan: true
