name: Build and Deploy GitBook

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14' # 16 no workie, let's try 14
        
    - name: Install GitBook CLI
      run: |
        npm install -g gitbook-cli --force
        gitbook fetch 3.2.3
        
    - name: Build GitBook
      run: gitbook build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book
